int anoNasc;
int anoAtual = DateTime.Now.Year;
Console.SetCursorPosition(10, 5);
Console.Write("Em que ano você nasceu? ");
int.TryParse(Console.ReadLine(), out anoNasc);
Thread.Sleep(300);
Console.WriteLine("---------------------------------------");
Thread.Sleep(500);
Console.WriteLine($"Estamos no ano de {anoAtual}");
Thread.Sleep(500);
Console.WriteLine($"Quem nasceu em {anoNasc}, tem {anoAtual - anoNasc} anos");
Console.ReadKey();